version: "3.8"
services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    restart: unless-stopped
    environment:
      TELEGRAM_API_ID: "your api id"   
      TELEGRAM_API_HASH: "your api hash"
    ports:
      - "8081:8081"   
    volumes:
      - tg-bot-api-data:/var/lib/telegram-bot-api
volumes:
  tg-bot-api-data:
